### ISSUE TITLE
Failed updating localplayer

### ISSUE THREAD

**Issue by Dakuldude** [Xaxoxuxu/CSGO-External-Simple-Hax#1]
Failed updating localplayer

Unless I'm building the project wrong in c++ then there is an issue with the injection

**Comment by JoelLuzi** [comment]
make sure the offsets are correct

**Comment by LightBeam01** [comment]
make sure the offsets are korrect

**Comment by stdNullPtr** [comment]
I just updated the offsets in master, it should be working.
